version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: alessandro
      POSTGRES_PASSWORD: ciaobelli
      POSTGRES_DB: dw_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
