version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: alessandro
      POSTGRES_PASSWORD: ciaobelli
      POSTGRES_DB: dw_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:


 jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://etl_user:etl_password@postgres:5432/economic_data
